### ISSUE TITLE
'parentView._slots' is undefined within ember-wormhole

### ISSUE THREAD

**Issue by XaserAcheron** [ciena-blueplanet/ember-block-slots#30]
I'm trying to use this addon in conjunction with [ember-wormhole](https://github.com/yapplabs/ember-wormhole), and [Line 56 of yield-slot.js](https://github.com/ciena-blueplanet/ember-block-slots/blob/master/addon/components/yield-slot.js#L56) is throwing a TypeError as `parentView._slots` is undefined. I suspect `parentView` is resolving to the `ember-wormhole` component rather than my `SlotsMixin`-derived custom component, hence why it can't find `_slots`.

Apologies for the vagueness; just have time to drop a quick note. I'll see if I can come up with a better test case, since this likely isn't really a wormhole-specific thing but more a general issue with trying to put the `yield-slot`s inside a component block.

**Comment by sglanzer-fire** [comment]
Interesting case - I suspect you're correct and the wormhole is the actual parent in this case.  If you can throw together a sample repo I would be happy to help fix this case - we solved a lot of corner cases around the 'clever' lookup of the _slots, but I forgot to consider this one

**Comment by XaserAcheron** [comment]
This still isn't a true demo, but I was playing around with it again and found that it seems to trigger any time you try and nest the yield slots within another component. Quick n' dirty sample:

``` handlebars
{{!-- app/templates/super-cool-block-test.hbs --}}
{{#another-component}}
    {{yield}}
    {{#yield-slot 'cool'}}
        {{yield}}
    {{/yield-slot}}
{{/another-component}}
```

Trying to drop a `super-cool-block-test` into a page will result in the error described in the initial post -- `parentView` is resolving to `another-component` rather than `super-cool-block-test`.

I wonder if it's possible to make it relative to the initial `{{yield}}`, such that it will work as intended as long as you first yield inside the block component (as in the example above). Either that or recursively call `parentView`, if Ember allows that (although that'd break the computed property update check... ick).

Side-suggestion: a check inside the computed property that throws a more explicit error if `parentView._slots` is missing would be handy too.

**Comment by sglanzer-fire** [comment]
Ah, I think I know what you're hitting with this one, we need to change this https://github.com/ciena-blueplanet/ember-block-slots/blob/master/addon/components/yield-slot.js#L55 (parentView) to use this strategy https://github.com/ciena-blueplanet/ember-block-slots/blob/master/addon/components/block-slot.js#L42 (nearestOfType)

I had asked a colleague to make the change recently, but it hasn't happened yet.  I'd be happy to accept a PR, or I'll get to this mid-week myself.

**Comment by XaserAcheron** [comment]
Ah, that ought to do it. I'll see if I can draft a PR sometime soonish. Thanks for taking a look!

**Comment by XaserAcheron** [comment]
Darn. This may be a bit less simple than I thought.

I just set up a local environment and swapped the `parentView` check to use`nearestOfType` & `_isRegistered`, like so...

``` javascript
  isActive: computed('parentView._slots.[]', '_name', function () {
    return this.nearestOfType(Slots)._isRegistered(this.get('_name'))
  })
```

...and it fixes the 'crash' right up. Trouble is, I'm not sure what to replace the computed property condition (`'parentView._slots.[]'`) with. The end result is `isActive` is failing to update if a slot is _activated or _deactivated, meaning the `yield-slot`'s `else` default no longer shows if I trigger an action which removes its corresponding `block-slot` from the page. Doh!

Any ideas on this? I'll see if I can noodle up something, since I won't consider this PR-ready until it's fixed. No sense in fixing an obvious bug only to introduce a more subtle one. ;)

**Comment by XaserAcheron** [comment]
Herp and derp. Figured out an obvious how-to-do-it right after posting that. Will PR soonish.

Remember, Emberfolk: when in doubt, Computed Properties Solve Everything™.
