### ISSUE TITLE
Add blueprints

### ISSUE THREAD

**Issue by sandersky** [ciena-blueplanet/ember-block-slots#33]
Recently `ember-prop-types` upgraded from version `2.0.1` to version `2.0.0` which stopped including `ember-lodash` as a dependency in favor of providing `ember-lodash-shim` via blueprints. This project should be using blueprints and include `ember-prop-types` in it's blueprints which will make is so running `ember install ember-block-slots` will run the ember install of `ember-prop-types`, causing the consumer to also get `ember-lodash-shim` which is required for that project to work.

**Comment by JackCA** [comment]
Just chiming in here since I opened the original issue, and excuse me if this isn't productive or off-topic.

That being said, I realize that these two projects are both being worked on by the same team and dog-fooding is great, but I think it's a bit heavy to enforce lodash to be a dependency of this project (via `ember-prop-types`).

Is `ember-prop-types` valuable enough to this project that users of `ember-block-slots` need it as a dependency?

**Comment by sandersky** [comment]
@JackCA if you want you can file an issue on `ember-prop-types` to remove the lodash dependency. I'm pretty sure it is only using a few functions from lodash and the dependency could be removed with little effort I think.

**Comment by JackCA** [comment]
@sandersky awesome, I've opened that issue in `ember-prop-types`. Feel free to free to ignore my comment above in regards to this specific issue.

**Comment by sglanzer-fire** [comment]
@JackCA it's a very good point and something I was thinking about recently - I think we need to reduce the dependency tree for all of our 'core' addons

In the case of ember-prop-types it might be best to just package in a custom lodash dist and drop the dependency

**Comment by sglanzer-fire** [comment]
We're going to take a look at the above as a solution - should have a pr available shortly

**Comment by sglanzer-fire** [comment]
@JackCA the latest ember-prop-types removes the lodash dependency - I believe this can be closed

**Comment by JackCA** [comment]
@sglanzer yes, I saw that and that's awesome!

However, I've never created a publicly consumed ember addon, but it's possible adding the blueprint could still be a good idea/best practice.

Maybe @sandersky can chime in?

**Comment by sglanzer-fire** [comment]
@JackCA - ah yes, good point - 😴 brain

**Comment by sglanzer-fire** [comment]
Fixed by #36
