### ISSUE TITLE
Fails to build in new Ember app

### ISSUE THREAD

**Issue by ianstarz** [ciena-blueplanet/ember-block-slots#37]
Just ran `ember new plz`, installed block slots, and then get the following:

```
➜  plz git:(master) cat package.json
{
  "name": "plz",
  "version": "0.0.0",
  "description": "Small description for plz goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.7.0-beta.5",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.7.0-beta.1",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
  }
}
➜  plz git:(master) ember install ember-block-slots
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
installing ember-block-slots
  install addon ember-prop-types@^2.0.0
Installed packages for tooling via npm.
Installed addon package.
Installed addon package.
➜  plz git:(master) ✗ ember s
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'app' of undefined
TypeError: Cannot read property 'app' of undefined
    at CoreObject.extend.import (/Users/istorz/Desktop/plz/node_modules/ember-cli/lib/models/addon.js:424:15)
    at CoreObject.extend.import (/Users/istorz/Desktop/plz/node_modules/ember-cli/lib/models/addon.js:427:15)
    at CoreObject.module.exports.importPolyfill (/Users/istorz/Desktop/plz/node_modules/ember-cli-babel/index.js:35:18)
    at CoreObject.module.exports.included (/Users/istorz/Desktop/plz/node_modules/ember-cli-babel/index.js:65:12)
    at CoreObject.superWrapper [as included] (/Users/istorz/Desktop/plz/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at /Users/istorz/Desktop/plz/node_modules/ember-cli/lib/models/addon.js:258:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/Users/istorz/Desktop/plz/node_modules/ember-cli/lib/models/addon.js:256:24)
    at CoreObject.extend.included (/Users/istorz/Desktop/plz/node_modules/ember-cli/lib/models/addon.js:408:10)
    at CoreObject.superWrapper [as included] (/Users/istorz/Desktop/plz/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
➜  plz git:(master) ✗
```

**Comment by sglanzer-fire** [comment]
Possibly related to the way addons are supposed to import dependencies in ember-cli 2.7, we've stuck https://github.com/ember-cli/ember-cli-import-polyfill in a few places to compensate.

I wouldn't have expected it in this scenario though since neither block-slots or the prop-types dependency make use of app.import

I'll see what I can do to dig into this

**Comment by ianstarz** [comment]
Thanks @sglanzer, let me know if I can help out at all.

On a side note, what might it take to avoid bringing in the polyfill? Are you guys blocked without it?

**Comment by sglanzer-fire** [comment]
We've been hit by the polyfill issue in numerous places, `ember-cli` does its best, but it isn't the most stable between minor releases.  I'll talk to @sandersky about this tomorrow, he may have a better idea of what is going on downstream.

**Comment by ianstarz** [comment]
Ah I see, sorry, I didn't understand your first comment. I'll try and take a look as well

**Comment by XaserAcheron** [comment]
I may have just hit something related after updating `ember-block-slots`, though the exact error message I got was `"app.import is not a function"` when trying to run `ember server`. Seems to be the same sort of deal, googling around a bit, though the issue was fixed on my side by updating to `ember-cli` v2.7.0, so I may be seeing the other side of the coin.

Dunno if this helps, but there you go.

**Comment by ianstarz** [comment]
@XaserAcheron thanks, that's how I first ran into the issue as well. Upgrading ember-cli hides the fact that somewhere downstream is requiring the browser-polyfill.js which is 4500 LOC our team doesn't want to ship.

**Comment by sglanzer-fire** [comment]
It's something to do with how addons use `app.import` and it's supposed to be shifting to `this.import`, but it requires a polyfill to work in the meantime...feels like a breaking change in a minor release from `ember-cli`, but maybe they didn't consider that a public API

**Comment by sglanzer-fire** [comment]
This project uses app.import, but in the `ember-cli-build` not in the `index`, so I have to believe this is a problem with a downstream dependency.  I have heard that including https://github.com/ember-cli/ember-cli-import-polyfill in consuming apps is the way to currently fix this

**Comment by rox163** [comment]
references for the app.import issue - https://github.com/ember-cli/ember-cli/pull/5877
https://github.com/ember-cli/rfcs/pull/63

To work around the issue for consuming apps/addons pre ember-cli 2.7, install the import polyfill in your consuming apps/addons and use like so - https://github.com/tomdale/ember-network/pull/7/files

**Comment by ianstarz** [comment]
I'm fine with closing this issue since `ember-cli-import-polyfill` fixes the problem. Sad though, the browser-polyfill is something our team doesn't want to include in our payload; atm it's a blocker for us using ember-block-slots..

**Comment by sglanzer-fire** [comment]
I'm reopening this so that we can chase the downstream issue - we just need to identify which addon needs to be updated and raise an issue against that project

**Comment by ianstarz** [comment]
i believe this is it https://github.com/ciena-blueplanet/ember-prop-types/blob/master/index.js#L6-L18

**Comment by sglanzer-fire** [comment]
@sandersky @rox163 anything we can do about ^?

**Comment by ianstarz** [comment]
going to try https://github.com/ciena-blueplanet/ember-prop-types/pull/52 in our project and see if anything breaks, all tests seem to pass

**Comment by ianstarz** [comment]
ciena-blueplanet/ember-prop-types#52 did the trick; new ember apps on old ember-cli run just fine now. Thanks for your help everyone!
