### ISSUE TITLE
Conditional yield-slot only renders else content, not the yield content

### ISSUE THREAD

**Issue by benbabics** [ciena-blueplanet/ember-block-slots#47]
This looks incredible. Very eager to use it, however, for my simplest of test, it doesn't seem to work. I'm pretty sure I've implemented this correctly, but would be happy for you to point out a mistake on my part to make this work. :)

**components/header-page/component.js**
```
import Ember from 'ember';
import SlotsMixin from 'ember-block-slots';

export default Ember.Component.extend(SlotsMixin, {});

```

**components/page-header/template.hbs**
```
<h2>
  {{#yield-slot 'title'}}
    Yes: {{yield}}
  {{else}}
    No: Default Title
  {{/yield-slot}}
</h2>
```

**index/template.hbs**
```
{{#header-page}}
  {{#block-slot 'title'}}My Title{{/block-slot}}
{{/header-page}}
```

The result is always: "*No: Default Title*", if `#block-slot 'title'` exists or not. Any help is much appreciated.

**Comment by benbabics** [comment]
Btw I'm running Ember 2.6.2.

**Comment by benbabics** [comment]
Boy do I feel sheepish... I entirely missed the text 

> "In the component template, yield once to allow instances to register block slots, then provide one or more named yield slots"

Ok, pls ignore. Thx.

**Comment by sglanzer-fire** [comment]
No sweat, happy to see more people use this 👍
