### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by allthesignals** [ciena-blueplanet/ember-block-slots#56]
I tried to use block slots and I'm seeing this error:

`Uncaught TypeError: Cannot read property 'includes' of undefined`

Maybe I just don't understand how the API works

**Comment by janmisek** [comment]
@allthesignals 

You probably forget to include the mixin on the component which is yielding slots.

```
import Component from '@ember/component';
import SlotsMixin from 'ember-block-slots';

export default Component.extend(
  SlotsMixin, 
  {
     ...
  }
);
```

**Comment by allthesignals** [comment]
I’m at goof! 🤡
