### ISSUE TITLE
Incorrect parsing of htmlbar block quotes in demo app when using {{format-markdown}}  

### ISSUE THREAD

**Issue by juwara0** [ciena-blueplanet/ember-block-slots#9]
We are experiencing this issue: https://github.com/isagalaev/highlight.js/issues/1130 open against highlight.js that causes our htmlbars block quotes to not display correctly in the demo app.

**Comment by sglanzer-fire** [comment]
We've replaced `format-markdown` with `ember-code-snippets`, so this no longer impacts the demo
